# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: XrEfKKXLthETlbTSx3nD3TOZBrhXPDVa
            client-secret: HoBi1uy1IxRJVyC7dHdXKswKobX6isPz3skO7oniKFlw5K8MCX1i0AmvmRs0sATy
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-b508xsv1.us.auth0.com/